### ISSUE TITLE
Please push 0.13.0 as latest

### ISSUE THREAD

**Issue by drewwells** [keyvanfatehi/docker-sinopia#11]
docker build -t keyvanfatehi/docker-sinopia:latest keyvanfatehi/docker-sinopia:0.13.0

You can remove the versions from all of the instructions after doing this.

**Comment by brunobatista** [comment]
+1

**Comment by drewwells** [comment]
Docker hub will automatically build git updates. However, you will lose the
ability to push your own. I'd point to a number of projects already doing
this for how to maintain the tagging you want:
https://github.com/docker-library/golang

**Comment by keyvanfatehi** [comment]
The docker hub won't allow me to manually push the latest tag :(

I think folks are better off building their own custom image. This image can serve as a reference for building your own images.

**Comment by keyvanfatehi** [comment]
This Docker repository is bugged, see https://github.com/keyvanfatehi/docker-sinopia/issues/7 For future updates please search for sinopia on the docker hub or fork my github repository and build your own using mine as a reference.

I am closing down issues on this repository as a result of their inaction and the fact that building your own is preferable at this point.

**Comment by keyvanfatehi** [comment]
I deleted the Docker repo and rebuilt everything so "latest" automated builds are working now. :)

**Comment by brunobatista** [comment]
Thanks @keyvanfatehi :+1:

**Comment by keyvanfatehi** [comment]
@brunobatista no problem. I just added you as a collaborator so you can push to this repository anytime you would like to cause a rebuild to occur

**Comment by keyvanfatehi** [comment]
Also added @kurtharriger and @drewwells
