### ISSUE TITLE
Bump for 1.0.0 alphas?

### ISSUE THREAD

**Issue by pluma** [keyvanfatehi/docker-sinopia#12]
Although 1.0.0 proper isn't out yet, it'd be awesome if the alpha releases could be tracked for the time being to make upgrading easier.

**Comment by keyvanfatehi** [comment]
Please make your own, feel free to use mine as a reference... but my docker hub repository is bugged and Docker doesn't seem to care to fix ( ref https://github.com/keyvanfatehi/docker-sinopia/issues/7 )

**Comment by keyvanfatehi** [comment]
I deleted the Docker repo and rebuilt everything so "latest" automated builds are working now. I removed the version stipulation in the "npm install" command, so now it downloads whatever rkwilda is releasing to npm. I won't manually stipulate the version anymore.
