### ISSUE TITLE
should have a latest tag to allow easy upgrades

### ISSUE THREAD

**Issue by preflightsiren** [keyvanfatehi/docker-sinopia#7]
If you tag each release as latest, then I can just pull sinopia:latest and get new version.

**Comment by keyvanfatehi** [comment]
as of this message, this bug still exists on the docker hub... I asked for an update in at the support.docker.com page pictured above...

**Comment by keyvanfatehi** [comment]
This Docker repository is bugged, see #7 For future updates please search for sinopia on the docker hub or fork my github repository and build your own using mine as a reference.

I am closing down issues on this repository as a result of their inaction and the fact that building your own is preferable at this point.
